# Generated by Django 6.0 on 2025-12-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='attended_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='conducted_classes',
            field=models.IntegerField(default=0),
        ),
    ]
